# ----------------------------------------------------------------------
# Pretraining PHOC
# ----------------------------------------------------------------------
enable_phoc: true        # turn PHOC loss on/off
phoc_levels: [1, 2, 3, 4] # same default as HTRNet
phoc_loss_weight: 0.1     # loss scaling factor

# ----------------------------------------------------------------------
# Default HTRNet architecture
# ----------------------------------------------------------------------
architecture:
  cnn_cfg: [[2, 64], "M", [3, 128], "M", [2, 256]]
  head_type: both
  rnn_type: gru
  rnn_layers: 3
  rnn_hidden_size: 256
  flattening: maxpool
  stn: false
  feat_dim: 512
  feat_pool: attn
  phoc_levels: [1, 2, 3, 4]

# ----------------------------------------------------------------------
# Soft‑contrastive loss 
# ----------------------------------------------------------------------
contrastive_enable: true   # turn on to activate the loss
contrastive_weight: 0.2     # β – scales the new loss inside total_loss
contrastive_tau: 0.07       # τ – temperature for descriptor similarities
contrastive_text_T: 1.0     # T_txt – softness in edit‑distance space

# ----------------------------------------------------------------------
# Optional pretrained backbone
# ----------------------------------------------------------------------
load_pretrained_backbone: false   # load weights for the backbone at startup
pretrained_backbone_path: "htr_base/saved_models/pretrained_backbone.pt"
