# ----------------------------------------------------------------------
# Backbone refinement
# ----------------------------------------------------------------------
refine_batch_size: 128      # mini-batch size used when fine-tuning the backbone
refine_lr: 1e-4             # learning rate during backbone refinement
refine_main_weight: 1.0     # weight for the main CTC loss branch
refine_aux_weight: 0.1      # weight for the auxiliary CTC loss

# ----------------------------------------------------------------------
# Projector training
# ----------------------------------------------------------------------
projector_epochs: 150       # number of epochs for the projector network
projector_batch_size: 4000  # mini-batch size when collecting descriptors
projector_lr: 1e-4          # learning rate for projector optimisation
projector_workers: 1        # dataloader workers used during descriptor caching
projector_weight_decay: 1e-4  # weight decay for the projector optimiser

# ----------------------------------------------------------------------
# Compute device
# ----------------------------------------------------------------------
device: cuda                # target device for training

# ----------------------------------------------------------------------
# Alternating training cycle
# ----------------------------------------------------------------------
alt_rounds: 4               # number of backbone/projector cycles per pass
alt_backbone_epochs: 10     # epochs for each backbone refinement phase
alt_projector_epochs: 200   # epochs for each projector training phase

# ----------------------------------------------------------------------
# Align-more-instances defaults
# ----------------------------------------------------------------------
align_batch_size: 512       # mini-batch size when harvesting descriptors
align_device: cpu           # device used during alignment post-processing
align_reg: 0.1              # entropic regularisation for Sinkhorn
align_unbalanced: false     # use unbalanced OT formulation
align_reg_m: 1.0            # mass regularisation when unbalanced OT is used
align_k: 200                  # pseudo-label this many least-moved descriptors
